import type { Metadata } from 'next'
import './globals.css'
import '@/assets/css/theme.min.css';
import '@/assets/vendor/boxicons/css/boxicons.min.css';
import '@/assets/vendor/swiper/swiper-bundle.min.css';
import Header from './ui/header';
import { Manrope } from 'next/font/google';

const manrope = Manrope({ subsets: ['latin'] } );

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Header />
        <main className="page-wrapper">
          {children}
        </main>
      </body>
    </html>
  )
}
